name: CD - Gerar Artefato

on:
  push:
    branches: [ "main" ]

jobs:
  delivery:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clonar repositório
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compilar projeto
        run: javac -d build main/Main.java

      - name: Rodar aplicação
        run: echo "5" | java -cp build main.Main

      - name: Gerar artefato
        run: |
          mkdir -p build
          cp *.class build/

      - name: Salvar artefato
        uses: actions/upload-artifact@v4
        with:
          name: projeto-cartas
          path: build/