name: CI - Build + Testes Unitários

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Baixar JUnit
        run: |
          curl -L -o junit-platform-console-standalone.jar \
          https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.14.2/junit-platform-console-standalone-1.14.2.jar

      - name: Compilar projeto
        run: |
          javac -d . model/*.java
          javac -d . service/*.java
          javac -d . util/*.java
          javac -d . view/*.java
          javac -d . main/*.java

      - name: Compilar testes
        run: |
          javac -cp ".:junit-platform-console-standalone.jar" -d . test/*.java

      - name: Rodar testes unitários
        run: |
          java -jar junit-platform-console-standalone.jar \
          --class-path . \
          --select-class CartaTeste \
          --select-class GeradorCartaTeste